### ISSUE TITLE
Build error, unbound module Model

### ISSUE THREAD

**Issue by einars** [jfeser/odoc2docset#1]
Running on a fresh archlinux, attempts to build — either via pinning via opam and letting it work its magic, or directly via dune — fail with

File "bin/main.ml", line 46, characters 11-21:
Error: Unbound module Model

I tried switching to earlier compiler versions, tried installing the exact versions of the packages mentioned in odoc2docset, assuming that something had provided Model, but is providing it no more — without success.

Which package is the Model supposed to come from?

**Comment by jfeser** [comment]
Sadly, this package relies on a patched version of odoc that exposes some of the internals (like the Model module). I'll stick it up on github when I get a chance.

**Comment by jfeser** [comment]
Try pinning odoc with `opam pin add odoc https://github.com/jfeser/odoc.git`.
