### ISSUE TITLE
how to build this project

### ISSUE THREAD

**Issue by nrolland** [jfeser/odoc2docset#3]
Is there some module missing ?

> File "bin/main.ml", line 46, characters 18-40:
> Error: Unbound module Model

```
let rec id_to_string =
  let module Id = Model.Paths.Identifier in
  ...
```

**Comment by jfeser** [comment]
Pin this copy of odoc first:
`opam pin add https://github.com/jfeser/odoc.git`

**Comment by avsm** [comment]
There is a handy but slightly obscure feature in opam 2.0 that might help with this called 'pin-depends'. You can use that field to specify packages that need to be pinned upstream automatically, such as odoc in this case.

Very cool looking tool btw! I look forward to trying this on my Mac with odoc and Dash :-)
