### ISSUE TITLE
Not installable - dependencies underspecified?

### ISSUE THREAD

**Issue by frou** [jfeser/odoc2docset#6]
Hi there. Thanks for creating this. I'm trying to install it and it seems like the dependencies are maybe underspecified in the dune/opam files.

Trying to install in a fresh 4.12.0 OPAM switch errors out, talking about the `shell` library not being found, but there may be more.

```txt
[ERROR] The compilation of odoc2docset failed at
        "/Users/holmdunc/.opam/opam-init/hooks/sandbox.sh build dune build -p
        odoc2docset -j 11 @install".

#=== ERROR while compiling odoc2docset.~dev ===================================#
# context     2.0.8 | macos/x86_64 | ocaml-base-compiler.4.12.0 | pinned(git+https://github.com/jfeser/odoc2docset.git#b490f684)
# path        ~/.opam/xyz/.opam-switch/build/odoc2docset.~dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p odoc2docset -j 11 @install
# exit-code   1
# env-file    ~/.opam/log/odoc2docset-74833-21fead.env
# output-file ~/.opam/log/odoc2docset-74833-21fead.out
### output ###
# File "bin/dune", line 5, characters 51-56:
# 5 |             logs.cli fmt.cli fmt.tty core cmdliner shell)
#                                                        ^^^^^
# Error: Library "shell" not found.
# Hint: try:
#   dune external-lib-deps --missing -p odoc2docset -j 11 @install
```

**Comment by jfeser** [comment]
Thanks for the report! The dev version is a mess right now. Have you tried 1.3.1?

Happy to take patches if you get the dependencies worked out.

**Comment by frou** [comment]
Thanks. Replacing the first command in the Readme with this worked:

`opam pin add odoc2docset https://github.com/jfeser/odoc2docset.git#32dfdd8aeae08a6dd0882ee335bf456bdf066cfb`

FWIW I maintain a Dash [docset](https://github.com/frou/ocaml-docset) based on OCaml's official HTML manual which I feel is in very good shape, but obviously that's limited to the the stdlib only.
